aodn/harvesters

workspace/ANMN_NRS_CTD_PROFILES/context/Metadata_0.1.item
workspace/ANMN_NRS_CTD_PROFILES/context/Metadata_0.1.properties
workspace/ANMN_NRS_CTD_PROFILES/process/ANMN_NRS_CTD_PROFILES_harvester_0.1.item
workspace/ANMN_NRS_CTD_PROFILES/process/ANMN_NRS_CTD_PROFILES_harvester_0.1.properties
workspace/ANMN_NRS_CTD_PROFILES/process/subjobs/UpdateMetadata_0.1.item
workspace/ANMN_NRS_CTD_PROFILES/process/subjobs/UpdateMetadata_0.1.properties

The iUpdateSpatialExtent component is failing because Metadata_SpatialTable is pointing to a non-existent table. This should fix it.
Databags in production will need to be updated.

ANMN_NRS_CTD_PROFILES: fix parameters for spatial update

---

workspace/AODN_CSIRO_CMAR/context/MetadataADCP_0.1.item
workspace/AODN_CSIRO_CMAR/process/aodn_csiro_cmar_harvester_0.1.item
workspace/AODN_CSIRO_CMAR/process/aodn_csiro_cmar_subjobs/UpdateMetadata_0.1.item

Revert "aodn_csiro_cmar: parameters conform naming convention"

---

workspace/WODB/context/Destination_0.1.properties
workspace/WODB/process/Harvest_data_0.1.properties
workspace/WODB/process/Harvest_metadata_0.1.properties
workspace/WODB/process/WODB_data_harvester_0.1.properties
workspace/WODB/process/subjobs/Harvest_apb_0.1.properties
workspace/WODB/process/subjobs/Harvest_apb_data_0.1.properties
workspace/WODB/process/subjobs/Harvest_ctd_0.1.properties
workspace/WODB/process/subjobs/Harvest_ctd_data_0.1.properties
workspace/WODB/process/subjobs/Harvest_gld_0.1.properties
workspace/WODB/process/subjobs/Harvest_gld_data_0.1.item
workspace/WODB/process/subjobs/Harvest_gld_data_0.1.properties
workspace/WODB/process/subjobs/Harvest_mbt_0.1.properties
workspace/WODB/process/subjobs/Harvest_mbt_data_0.1.properties
workspace/WODB/process/subjobs/Harvest_osd_0.1.properties
workspace/WODB/process/subjobs/Harvest_osd_data_0.1.properties
workspace/WODB/process/subjobs/Harvest_pfl_0.1.properties
workspace/WODB/process/subjobs/Harvest_pfl_data_0.1.properties
workspace/WODB/process/subjobs/Harvest_sur_0.1.properties
workspace/WODB/process/subjobs/Harvest_sur_data_0.1.properties
workspace/WODB/process/subjobs/Harvest_uor_0.1.properties
workspace/WODB/process/subjobs/Harvest_uor_data_0.1.properties
workspace/WODB/process/subjobs/Harvest_xbt_0.1.properties
workspace/WODB/process/subjobs/Harvest_xbt_data_0.1.properties

@anguss00  : check only  the Harvest_gld_data_0.1.item file.
The other changes are just  creation date changes by talend.

changed variable time type from date to string in Tmap

---

workspace/ANMN_ACIDIFICATION_NRT/context/Metadata_0.1.item
workspace/ANMN_ACIDIFICATION_NRT/context/Metadata_0.1.properties
workspace/ANMN_ACIDIFICATION_NRT/process/ANMN_acidification_nrt_harvester_1.0.item
workspace/ANMN_ACIDIFICATION_NRT/process/ANMN_acidification_nrt_harvester_1.0.properties
workspace/ANMN_ACIDIFICATION_NRT/process/Subjobs/UpdateMetadata_0.1.item
workspace/ANMN_ACIDIFICATION_NRT/process/Subjobs/UpdateMetadata_0.1.properties
workspace/ANMN_ACIDIFICATION_NRT/talend.project

* add metadata spatial component

ANMN_ACIDIFICATION_NRT metadata

---

workspace/ABOS_SOFS_SURFACE_FLUXES/context/Destination_0.1.item
workspace/ABOS_SOFS_SURFACE_FLUXES/context/Destination_0.1.properties
workspace/ABOS_SOFS_SURFACE_FLUXES/context/Source_0.1.item
workspace/ABOS_SOFS_SURFACE_FLUXES/context/Source_0.1.properties
workspace/ABOS_SOFS_SURFACE_FLUXES/process/ABOS_SOFS_surfaceflux_harvester_1.0.item
workspace/ABOS_SOFS_SURFACE_FLUXES/process/ABOS_SOFS_surfaceflux_harvester_1.0.properties
workspace/ABOS_SOFS_SURFACE_FLUXES/process/Subjobs/DeleteSOFSFileData_0.1.item
workspace/ABOS_SOFS_SURFACE_FLUXES/process/Subjobs/DeleteSOFSFileData_0.1.properties
workspace/ABOS_SOFS_SURFACE_FLUXES/process/Subjobs/HarvestSOFSFile_0.1.item
workspace/ABOS_SOFS_SURFACE_FLUXES/process/Subjobs/HarvestSOFSFile_0.1.properties
workspace/ABOS_SOFS_SURFACE_FLUXES/process/Subjobs/UpdateMetadata_0.1.item
workspace/ABOS_SOFS_SURFACE_FLUXES/process/Subjobs/UpdateMetadata_0.1.properties
workspace/ABOS_SOFS_SURFACE_FLUXES/process/Subjobs/UpdateSOFStimeseriesTable_0.1.item
workspace/ABOS_SOFS_SURFACE_FLUXES/process/Subjobs/UpdateSOFStimeseriesTable_0.1.properties

@lbesnard I hope this will fix the errors in RC. Please test.

ABOS_SOFS_SURFACE_FLUXES: fix missing fileId context

---

workspace/SOOP_AUSCPR/process/SOOP_AUSCPR/subjobs/auscp_zoop_taxon_changelog_harvest_0.1.item
workspace/SOOP_AUSCPR/process/SOOP_AUSCPR/subjobs/auscp_zoop_taxon_changelog_harvest_0.1.properties

* fix last metadata_URL not being used in ZOOP

SOOP AUSCPR - zoop metadata url

---

bin/jenkins-trigger-helper.sh

* allow rebuild (pass --rebuild)
* ignore some blank harvesters (and report them)

improve jenkins build trigger

---

workspace/AATAMS_ACOUSTIC_REPORTING/process/aatams_acoustic_harvester_0.1.item
workspace/AATAMS_ACOUSTIC_REPORTING/process/aatams_acoustic_harvester_0.1.properties

@danfruehauf that should fix it, please merge and re-deploy.

AATAMS_ACOUSTIC_REPORTING: Tick box in main job to transmit whole context for metadata update subjob

---

README.md
bin/get-source-context-repository-id.xsl
bin/update-harvester.sh
bin/update-process-item.xsl
bin/update-source-context.xsl

Add a convert to manifest harvesting script

---

workspace/SOOP_XBT_DM/process/SOOP_XBT_DM_harvester_0.1.item
workspace/SOOP_XBT_DM/process/SOOP_XBT_DM_harvester_0.1.properties

Revert "SOOP XBT DM - restart *_map query disables during migration"

---

workspace/SOOP_XBT_DM/process/SOOP_XBT_DM_harvester_0.1.item
workspace/SOOP_XBT_DM/process/SOOP_XBT_DM_harvester_0.1.properties

Revert "Revert "SOOP XBT DM - restart *_map query disables during migration""

---

workspace/AATAMS_ACOUSTIC_REPORTING/process/AATAMS_acoustic_subjobs/Copy_Tables_0.1.item
workspace/AATAMS_ACOUSTIC_REPORTING/process/AATAMS_acoustic_subjobs/Populate_layers_0.1.item
workspace/AATAMS_ACOUSTIC_REPORTING/process/AATAMS_acoustic_subjobs/Populate_reporting_views_0.1.item

Addresses https://github.com/aodn/harvesters/issues/311.
I still got an I/O error when testing this harvester on my VM @jonescc, let's see how rc behaves with the changes made to

Change all truncates in iPostgresqlOutput to clear

---

workspace/AATAMS_SATTAG_NRT/process/aatams_sattag_nrt_subjobs/Create_map_table_0.1.item

Addresses https://github.com/aodn/content/issues/359 @jonescc

Changed TRUNCATE TO CLEAR for AATAMS_SATTAG_NRT

---

workspace/ANMN_NRS_BGC/process/ANMN_NRS_BGC/ANMN_NRS_BGC_harvester_0.1.item
workspace/SOOP_AUSCPR/process/SOOP_AUSCPR/SOOP_AUSCPR_harvester_0.1.item

Revert "Set TLS 1.2 for default on CSIRO endpoint harvesters"

---

workspace/AUS_PHYTO_DB/code/routines/NetCDFUtils_0.1.properties

Include netcdf 4.6.4 dependency required for NetCDFUtils routine

Fix AUS_PHYTO_DB dependency problems for TOS 7.1.1 migration

---

workspace/AUS_CHLA_DB/code/routines/NetCDFUtils_0.1.properties

Includes missing netcdf dependency for NetCDFUtils.

Fix AUS_CHLA_DB dependency problems for migration to TOS 7.1.1

---

workspace/TSUNAMI_BUOYS/.project
workspace/TSUNAMI_BUOYS/talend.project

This allows the project to be opened up in TOS.

Fix project rename

---

workspace/SOOP_BA/process/SOOP_BA/subjobs/UpdateMetadata_0.1.item
workspace/SOOP_BA/process/SOOP_BA/subjobs/harvest_soop_ba_metadata_0.1.item
workspace/SOOP_BA/process/SOOP_BA/subjobs/harvest_soop_ba_metadata_0.2.item
workspace/SOOP_BA/process/Utils/CreateTalendGATT_SchemasFromMetadata2_0.1.item
workspace/SOOP_BA/process/Utils/CreateTalendSchemasFromMetadata_0.1.item
workspace/SOOP_BA/process/harvestMetadata_filesystem/HarvestMetadataFromFileSystem_0.1.item
workspace/SOOP_BA/process/harvestMetadata_filesystem/Subjobs/DeleteMetadata_0.1.item
workspace/SOOP_BA/process/harvestMetadata_filesystem/Subjobs/HarvestFileSystemMetadata_0.1.item
workspace/SOOP_BA/talend.project

I _think_ this is right. @jonescc I updated all the elements with `FIELDSEPARATOR` to have the value as per your other harvester fix

update field separators for soop_ba

---

Jenkinsfile

rather than bash
Global script added in https://github.com/aodn/jenkins-shared-library/pull/2

Work out harvester job name using global script

---

workspace/NRMN/process/NRMN_subjobs/Harvest_Data_0.1.item

Fix survey_date pattern to use MM (month) and not mm (minute).

Fix survey_date pattern in NRMN harvester
